import type { Metadata } from "next";
import "@/app/globals.css";
import { QueryProvider } from "@/shared";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Connectors",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon-32x32.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Suspense fallback={<div></div>}>
          <QueryProvider>
            <div className="flex h-screen min-h-screen w-[32rem] items-center">
              {children}
            </div>
          </QueryProvider>
        </Suspense>
      </body>
    </html>
  );
}
