import type { Metadata } from 'next';
import './globals.css';
import { QueryProvider } from './providers/queryProvider';

export const metadata: Metadata = {
  title: 'Connectors',
  description: 'Generated by create next app',
  icons: {
    icon: './favicon-32x32.png', // favicon 적용
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          width: '100%',
          minHeight: '100vh',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
        }}
      >
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
