name: Build and Deploy

on:
  push:
    branches: [dev]
  workflow_dispatch: # 수동 실행 가능

env:
  APP_NAME: ${{ secrets.APP_NAME }}
  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ env.CONTAINER_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to server
        env:
          PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            docker pull ${{ env.IMAGE_NAME }}:${{ github.sha }} &&
            docker stop ${{ env.CONTAINER_NAME }} || true &&
            docker rm ${{ env.CONTAINER_NAME }} || true &&
            docker run -d --name ${{ env.CONTAINER_NAME }} -p 3000:3000 --restart unless-stopped ${{ env.IMAGE_NAME }}:
